name: 🐛 Bug 反馈
description: 遇到的任何问题都可以反馈！
labels: ['Type: Bug']
title: '【BUG】'
body:
    - type: dropdown
      attributes:
          label: 出现位置
          description: 你可以在此处指出该 Bug 出现于本项目的哪个位置。
          options:
              - 构建过程
              - 页面
              - 页面组件
              - 代码逻辑
              - 其它，请在后续详细补充
      validations:
          required: true

    - type: input
      attributes:
          label: Bug 出现的版本
          description: 在此处输入 Bug 出现时项目的版本或分支，若不填写则默认为网站生产环境的版本。
          placeholder: 分支可直接写分支名称，版本直接写 commit hash 即可。如果填版本号，则默认按照网站生产环境分支处理。

    - type: textarea
      attributes:
          label: 具体表现
          description: 你可以在此处描述该问题出现的具体情况，包括但不限于复现步骤、报错时的提示或日志等等。
      validations:
          required: true

    - type: textarea
      attributes:
          label: 预期表现
          description: 你可以在此处描述你所希望的发生情形。
      validations:
          required: true

    - type: dropdown
      attributes:
          label: 该 Bug 的优先级
          description: 你可以在此处表述你希望该 Bug 得到开发者注意的优先级怎么样。
          options:
              - 高
              - 中
              - 低

    - type: checkboxes
      attributes:
          label: 提交 Issue 前须知
          options:
              - label: 我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue 或相似/同类型的 Issue。
                required: true
