name: 🐛 Bug 反馈
description: 遇到的任何问题都可以反馈！
labels: ["Bug"]
title: "【BUG】"
body: 
  - type: dropdown
    attributes:
      label: 出现位置
      description: 你可以在此处指出该 Bug 出现于本项目的哪个位置。
      options:
        - label: 构建过程（Node）
          required: true
        - label: 生产模式页面（Browser）
          required: true
        - label: 开发模式页面（Browser）
          required: true
        - label: 操作逻辑
          required: true
        - label: 其它，请在后续详细补充
          required: true
      
  - type: textarea
    attributes:
      label: 具体表现
      description: 你可以在此处描述该问题出现的具体情况，包括但不限于复现步骤、报错时的提示或日志等等。
    validations:
      required: true

  - type: textarea
    attributes:
      label: 预期表现
      description: 你可以在此处描述你所希望的发生情形。
    validations:
      required: true

  - type: select
    attributes: 
      label: 该 Bug 的优先级
      description: 你可以在此处表述你希望该 Bug 得到开发者注意的优先级怎么样。
      options: 
        - label: 高
        - label: 中
        - label: 低

  - type: checkboxes
    attributes:
      options:
        - label: 我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue 或相似/同类型的 Issue。
          required: true
