name: 🚀 新功能提议
description: 想要啥新功能都可以建议！
labels: ["Feature"]
title: "【FEAT】"
body: 

  - type: dropdown
    attributes:
      label: 类型
      description: 你可以在此处指出你想要的功能隶属于哪个类别。
      options:
        - UI & 设计
        - 独立页面（如版本页面）
        - 页内大版面组件
        - 页内小部件
        - 操作逻辑
        - 其它，请在后续详细补充
    validations:
        required: true
  
  - type: textarea
    attributes:
      label: 具体要求
      description: 你可以在此处描述你希望增加的功能的具体信息。
    validations:
      required: true

  - type: dropdown
    attributes: 
      label: 该请求的优先级
      description: 你可以在此处表述你希望该功能请求得到注意的优先级怎么样。
      options: 
        - 高
        - 中
        - 低

  - type: checkboxes
    attributes: 
      label: 提交 Issue 前须知
      options:
        - label: 我已经查看近期 Issues（包含 Open 和 Closed），未发现已存在此 Issue 或相似/同类型的 Issue。
          required: true
